version: '3.8'

services:
  app:
    image: currency-exchanger:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-exchanger
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/currency_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      FIXER_API_KEY: 6610c61cd1208fe9c29101b835b2174b
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgis/postgis:16-master
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_LISTEN_ADDRESSES: 'localhost'
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  db-data:
networks:
  internal:
    driver: bridge
